# Flatten visionOS bundle layout from macOS Contents/ structure to flat visionOS bundle
if (EXISTS "${BUNDLE_DIR}/Contents")
    message(STATUS "Flattening visionOS bundle at ${BUNDLE_DIR}")
    if (EXISTS "${BUNDLE_DIR}/Contents/Resources")
        file(COPY "${BUNDLE_DIR}/Contents/Resources/" DESTINATION "${BUNDLE_DIR}")
    endif ()
    if (EXISTS "${BUNDLE_DIR}/Contents/MacOS/Dusklight")
        file(RENAME "${BUNDLE_DIR}/Contents/MacOS/Dusklight" "${BUNDLE_DIR}/Dusklight")
    endif ()
    if (EXISTS "${BUNDLE_DIR}/Contents/Info.plist")
        file(RENAME "${BUNDLE_DIR}/Contents/Info.plist" "${BUNDLE_DIR}/Info.plist")
    endif ()
    file(REMOVE_RECURSE "${BUNDLE_DIR}/Contents")
endif ()
